service: aws-rust
provider:
  name: aws
  runtime: rust
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
        - xray:GetSamplingRules
        - xray:GetSamplingTargets
        - xray:GetSamplingStatisticSummaries
      Resource: '*'
package:
  individually: true
plugins:
  - serverless-rust
functions:
  hello:
    handler: hello
    runtime: provided